---
title: "03_Self-Learning_Supervised-Learning"
output: html_notebook
---

```{r - Objective of this exercise}
# Things to learn
# Libraries + Paralel Computing
# 
# 
# 

  
```

```{r - Load Libraries}

library(tidyr) # to reshape data
library(dplyr) # to transform data
library(ggplot2) # to vizualize data & display graph
library(rlang) # for tidy evaluation
library(forcats) # to manipulate fators
library(lubridate) # to work with dates
library(stringr) # to work with strings
library(purrr) # to work with functions and list


```

```{r - Load Data}

data <- read.csv("./data/avocado.csv")

data <- data %>%
  select(-X) %>% 
  mutate(Date=as.Date(Date,format="%Y-%m-%d")) %>% 
  arrange(Date)
  
pi
```

```{r}
x <- iris[which(iris[,5] != "setosa"), c(1,5)]
trials <- 10000
res <- data.frame()
system.time({
  trial <- 1
  while(trial <= trials) {
    ind <- sample(100, 100, replace=TRUE)
    result1 <- glm(x[ind,2]~x[ind,1], family=binomial(logit))
    r <- coefficients(result1)
    res <- rbind(res, r)
    trial <- trial + 1
  }
})

x <- iris[which(iris[,5] != "setosa"), c(1,5)]
trials <- seq(1, 10000)
boot_fx <- function(trial) {
  ind <- sample(100, 100, replace=TRUE)
  result1 <- glm(x[ind,2]~x[ind,1], family=binomial(logit))
  r <- coefficients(result1)
  res <- rbind(data.frame(), r)
}
system.time({
  results <- lapply(trials, boot_fx)
})
```
```{r}
library(parallel)
library(MASS)

starts <- rep(100, 40)
fx <- function(nstart) kmeans(Boston, 4, nstart=nstart)
numCores <- detectCores()
numCores

system.time(
  results <- lapply(starts, fx)
)

system.time(
  results <- mclapply(starts, fx, mc.cores = numCores)
)

system.time({
  results <- mclapply(trials, boot_fx, mc.cores = numCores)
})
```

```{r}
for (i in 1:3) {
  print(sqrt(i))
}

library(foreach)
foreach (i=1:3) %do% {
  sqrt(i)
}

```

